---
- name: Add PostgreSQL repository using lineinfile module
  shell: sh -c 'echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

- name: Download PostgreSQL repository signing key
  get_url:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    dest: /tmp/ACCC4CF8.asc

- name: Import PostgreSQL repository signing key
  shell: apt-key add /tmp/ACCC4CF8.asc


- name: Update all packages to their latest version
  package:
    name: "*"
    state: latest
    update_cache: yes

- name: Install "postgresql" packages
  apt:
    name:
      - postgresql-{{ postgresql_version }}
      - postgresql-contrib
    state: present

- name: "Find out if PostgreSQL is initialized"
  stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data

- name: Start "postgresql", if not started
  service:
    name: postgresql
    state: started

- name: Enable postgresql
  service:
    name: postgresql
    enabled: yes
  notify: restart postgresql


- name: Uninstall postgresql
  shell: apt remove postgresql -y
  when: uninstall_postgresql_debian
